name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install xmllint
      run: sudo apt -y install latexmk texlive-full

    - name: build main.pdf
      run: make

